export const SEARCH_FOR_LANGUAGE = 'SEARCH_FOR_LANGUAGE';
export const SEARCH_FOR_LANGUAGE_FAILED = 'SEARCH_FOR_LANGUAGE_FAILED';
export const SEARCH_FOR_LANGUAGE_SUCCEEDED = 'SEARCH_FOR_LANGUAGE_SUCCEEDED';

export const RESET_SEARCH_RESULTS = 'RESET_SEARCH_RESULTS';
